### ISSUE TITLE
bug: Query parameters passed to rest.restyClient methods aren't picked up

### ISSUE THREAD

**Issue by raamsri** [tinkershack/meteomunch#2]
### Problem:

`RestyClient.SetQueryParams()` and `RestyClient.SetQueryString()`doesn't work, but the query params get through if passed via RestyClient.Get()

### What's desired?:

Passed arguments must be respected and propagated for the HTTP request.

### Errors:
```bash
2024/10/03 01:40:09.913486 DEBUG RESTY
==============================================================================
~~~ REQUEST ~~~
GET  /packages/air-1h_air-day  HTTP/1.1
HOST   : my.meteoblue.com
HEADERS:
        User-Agent: go-resty/2.15.3 (https://github.com/go-resty/resty)
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 400 Bad Request
PROTO        : HTTP/1.1
RECEIVED AT  : 2024-10-03T01:40:09.913235+05:30
TIME DURATION: 1.457411964s
HEADERS      :
        Connection: keep-alive
        Content-Length: 82
        Content-Type: application/json; charset=utf-8
        Date: Wed, 02 Oct 2024 20:10:09 GMT
        Server: nginx
BODY         :
{
   "error_message": "Please specify an apikey in the url: &apikey=1234",
   "error": true
}
==============================================================================
{"time":"2024-10-03T01:40:09.913584+05:30","level":"ERROR","msg":"FAIL","tag":"server","err":"received error response: 400 Bad Request","description":"HTTP request failed!"}
2024/10/03 01:40:09 http: panic serving 127.0.0.1:53985: runtime error: invalid memory address or nil pointer dereference
goroutine 9 [running]:
net/http.(*conn).serve.func1()
        /usr/local/Cellar/go/1.23.1/libexec/src/net/http/server.go:1947 +0xbe
panic({0x5fa1da0?, 0x6347110?})
        /usr/local/Cellar/go/1.23.1/libexec/src/runtime/panic.go:785 +0x132
github.com/tinkershack/meteomunch/http/rest.(*Response).Status(...)
        /Users/raam/lab/code/tshack/gofly/meteomunch/http/rest/client.go:59
github.com/tinkershack/meteomunch/server.Serve.func2({0x6026bc0, 0xc0001782a0}, 0xc00014f040)
        /Users/raam/lab/code/tshack/gofly/meteomunch/server/server.go:68 +0x68d
net/http.HandlerFunc.ServeHTTP(0xc0001780e0?, {0x6026bc0?, 0xc0001782a0?}, 0x5d3f7b6?)
        /usr/local/Cellar/go/1.23.1/libexec/src/net/http/server.go:2220 +0x29
net/http.(*ServeMux).ServeHTTP(0x5a16839?, {0x6026bc0, 0xc0001782a0}, 0xc00014f040)
        /usr/local/Cellar/go/1.23.1/libexec/src/net/http/server.go:2747 +0x1ca
net/http.serverHandler.ServeHTTP({0xc00019ac00?}, {0x6026bc0?, 0xc0001782a0?}, 0x6?)
        /usr/local/Cellar/go/1.23.1/libexec/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc000140900, {0x6027318, 0xc00019ab10})
        /usr/local/Cellar/go/1.23.1/libexec/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/Cellar/go/1.23.1/libexec/src/net/http/server.go:3360 +0x485
{"time":"2024-10-03T01:40:09.917037+05:30","level":"INFO","msg":"/meteo","tag":"server"}
2024/10/03 01:40:10.745272 DEBUG RESTY
```

### How to reproduce?

1. Pull commit cfccacf7e6a324377e4bc2b359cc145c6b3fb295 that was merged with #1 
2. Comment out line 62 of file server/server.go
3. Change line 63 to this - `uri := fmt.Sprintf("packages/air-1h_air-day")`
4. Save the changes
5. Run `go run main.go server` on a terminal
6. Make a request to `http://localhost:50050/meteo` via curl or by visiting it in a web browser
7. Check the terminal output

```go
var client rest.HTTPClient = rest.NewClient().
			SetAuthToken("dummy-auth-token").
			// FIX: SetQueryParams() isn't getting picked up
			SetQueryParams(map[string]string{
				"lat":           "47.558",
				"lon":           "7.587",
				"asl":           "279",
				"tz":            "Europe/Zurich",
				"name":          "Test",
				"windspeed":     "kmh",
				"format":        "json",
				"history_days":  "1",
				"forecast_days": "0",
				"apikey":        cfg.MeteoProviders[0].APIKey,
			}).
			AcceptJSON().
			EnableTrace().
			SetDefaults().
			SetBaseURL(cfg.MeteoProviders[0].URI).
			SetDebug()
			// FIX: SetQueryString isn't getting picked up
			// SetQueryString("lat=47.558&lon=7.573&asl=279&tz=Europe%2FZurich&name=Test&windspeed=kmh&format=json&history_days=1&forecast_days=0&apikey=" + cfg.MeteoProviders[0].APIKey)

		// qs := "lat=47.558&lon=7.573&asl=279&tz=Europe%2FZurich&name=Test&windspeed=kmh&format=json&history_days=1&forecast_days=0&apikey=" + cfg.MeteoProviders[0].APIKey
		// uri := fmt.Sprintf("packages/air-1h_air-day?%s", qs)
                uri := fmt.Sprintf("packages/air-1h_air-day")
		resp, err := client.Get(uri)
		if err != nil {
			logger.Error(e.FAIL, "err", err, "description", "HTTP request failed!")
		}
```

### Expected output

```bash
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 200 OK
PROTO        : HTTP/1.1
RECEIVED AT  : 2024-10-03T01:43:38.507839+05:30
TIME DURATION: 766.470327ms
HEADERS      :
        Cache-Control: must-revalidate, no-cache, no-store, max-age=0
        Connection: keep-alive
        Content-Type: application/json; charset=utf-8
        Date: Wed, 02 Oct 2024 20:13:38 GMT
        Server: nginx
        Vary: Accept-Encoding
BODY         :
{
   "metadata": {
      "modelrun_updatetime_utc": "2024-10-02 20:13",
      "name": "Test",
      "height": 279,
      "timezone_abbrevation": "CEST",
      "latitude": 47.558,
      "modelrun_utc": "2024-10-02 20:13",
      "longitude": 7.573,
      "utc_timeoffset": 2.0,
      "generation_time_ms": 8.153915
   },
   "units": {
      "convectiveinhibition": "Jkg-1",
      "helicity": "m2s-2",
      "windspeed": "kmh",
      "cape": "Jkg-1",
      "freezinglevelheight": "m a.s.l.",
      "boundarylayerheight": "m",
      "cloudwater": "g",
      "time": "YYYY-MM-DD hh:mm",
      "temperature": "C",
      "probability": "percent",
      "pressure": "hPa",
      "cloudice": "g"
   },
   "data_1h": {
      "time": [
...
```

### Other necessary information

Test config used -

```yml
Munch:
  Server:
    HostName: "localhost"
    Port: "50050"
MeteoProviders:
  - Name: "meteoblue"
    APIKey: "redacted"
    URI: "http://my.meteoblue.com"
DocumentStore: "mongo"
MongoDB:
  Name: "mongo"
  URI: "mongodb://localhost:27017"
  DBName: "meteomunch"
DLMRedis:
  Name: "redis"
  URI: "localhost:6379"
  DBNumber: 11

```

Edit:
 - Included file path server/server.go
 - Included test config

**Comment by raamsri** [comment]
Resolved by #4 

@Yendelevium

**Comment by raamsri** [comment]
@Yendelevium , please do a quick check to assert whether the ability to chain HTTPClient interface methods is lost?

**Comment by yendelevium** [comment]
> @Yendelevium , please do a quick check to assert whether the ability to chain HTTPClient interface methods is lost?

@raamsri Just did, and I'm able to chain them just fine.. Just to be sure, u mean the ability to do 
client.SetAuthToken().SetQueryParams() stuff like that right?

**Comment by yendelevium** [comment]
Are you facing any problems with chaining? If so could you clarify..?

**Comment by raamsri** [comment]
`HTTPClient.NewRequest()` doesn't return the `HTTPClient` type. This fails a select set of sequence that chains NewRequest() following another method that is set at resty client level.

Consider this expression - `var client rest.HTTPClient = rest.NewClient().SetDebug().NewRequest()`. This wouldn't be possible because `NewRequest()` doesn't return a HTTPClient unlike the other methods that do return. 

This is something I haven't spent time understanding whether there might be another _particular_ way to use `NewRequest()` that must be enforced, but instead I called out right away to bring it to your notice. @Yendelevium Please correct me if I'm missing something, I'm a bit jaded after a rather long day.

**Comment by yendelevium** [comment]
@raamsri Hi, totally cool. What you're saying is right. But we had discussed yesterday in the library that we would rather do something like 

client.NewRequest()
client.SetAuthToken().SetQueryString() etc

Compared to chaining directly on NewRequest. That's why I didn't have it return HTTPClient type.

But in hindsight, i think returning HttpClient would be better, as this way we can chain it if we want, or just create a New request in the off chance that we don't want to chain, where we can then just discard the returned HttpClient or smtg. This way both options will be open.

**Comment by raamsri** [comment]
@Yendelevium I agree, and I had similar rationale so I put the required change in #6 already since it was only a minor change.

**Comment by yendelevium** [comment]
> @Yendelevium I agree, and I had similar rationale so I put the required change in #6 already since it was only a minor change.

Cool. I'll review #6 after classes.

**Comment by yendelevium** [comment]
Shouldn't we close this issue? With #6
